image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      cd /home/gitpod/.just/just
      make runtime
      sudo make install install-debug
      make -C modules/iouring library
      sudo make -C modules/iouring install install-debug
      exit