tasks:
  - init: |
      sh -c "$(curl -sSL https://raw.githubusercontent.com/just-js/just/current/install.sh)"
      make -C just clean runtime
      sudo make -C just install install-debug
      export JUST_HOME=$(pwd)/just
      export JUST_TARGET=$JUST_HOME
      make -C just/modules/iouring library
      sudo make -C just/modules/iouring install install-debug
    command: |
      just copy.js
